version: "3.9"

services:
  prestashop:
    image: prestashop/prestashop:${PS_VERSION}
    environment:
      - DB_SERVER=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}
      - DB_PREFIX=${DB_PREFIX}
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_DEMO_MODE=${PS_DEMO_MODE}
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO}
      - PS_DOMAIN=${PS_DOMAIN}:8080
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
    volumes:
      - type: bind
        source: .
        target: /var/www/html/modules/${PS_MODULE_NAME}  
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - prestashop-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    networks:
      - prestashop-net
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - prestashop-net

networks:
  prestashop-net:
volumes:
  db_data: {}